> Ch. 21


사용자로부터 이름과 나이를 입력 받아, "안녕하세요, [이름]님! 당신은 [나이]살입니다."라고 출력하는 함수 greet_user를 작성하세요.

In [1]:
def greeting(name, age):
    print(f'안녕하세요, {name}님! 당신은 {age}살입니다.')

greeting("oz", 20)

안녕하세요, oz님! 당신은 20살입니다.

> Ch. 22

여러 숫자를 입력받아 그 합계를 반환하는 함수 sum_numbers를 작성하세요. 이 때, 가변 매개변수를 사용하세요.

In [2]:
def sum_numbers(*numbers):
    return sum(numbers)

print(sum_numbers(1, 2, 3, 4, 5))

15

> Ch. 23


사용자의 이름을 출력하는 함수 print_name을 작성하세요. 만약 이름이 주어지지 않았다면, 기본값으로 "익명"을 사용하세요.

In [ ]:
def print_name(name='익명'):
    print(name)

print_name()
print_name('oz')

> Ch. 24

사용자의 이름, 나이, 성별을 출력하는 함수 print_info를 작성하세요. 이 때, 모든 매개변수는 키워드 매개변수로만 받도록 하세요.

In [ ]:
def print_info(**kwargs):
    for key, value in kwargs.items():
        print(f'{key}: {value}')

print_info(name='oz', age=20, gender='fem')

> Ch. 25

두 개의 정수를 받아 합을 반환하는 함수 add를 작성하세요. 매개변수와 반환값에 타입 어노테이션을 추가하세요.

In [ ]:
def add(x: int, y: int) -> int:
    return x + y

print(add(1, 2))

> Ch. 26

0부터 시작하여 n까지의 숫자 중에서 홀수만 생성하는 제너레이터 odd_numbers를 작성하세요.

In [35]:
n = 10
odd_numbers = (i for i in range(1, n+1, 2))

for num in odd_numbers:
    print(num)

1
3
5
7
9

In [31]:
# 참고
def odd_numbers(n):
    for i in range(n):
        if i % 2 != 0:
            yield i

print(odd_numbers(10))
for num in odd_numbers(10):
    print(num)

<generator object odd_numbers at 0x7802738bbd30>
1
3
5
7
9

In [34]:
def odd_numbers(n):
    return (i for i in range(1, n+1, 2))

print(type(odd_numbers(10)))
print(odd_numbers(10))
for num in odd_numbers(10):
    print(num)

<class 'generator'>
<generator object odd_numbers.<locals>.<genexpr> at 0x780273495cb0>
1
3
5
7
9

> Ch. 27

두 숫자를 더하는 람다 함수를 작성하고, 이를 변수에 할당한 후 사용하세요.

In [ ]:
add = lambda x, y: x + y

print(add(1, 2))

> Ch. 28

사용자로부터 3개의 숫자를 입력받아, 이를 튜플로 만든 후 최소값과 최대값을 출력하는 함수 min_max를 작성하세요.

In [23]:
def min_max(numbers):
    print('최소값:', min(numbers), '최댓값:', max(numbers))

num_tuple = tuple(map(int, input("3개의 숫자를 입력하세요: ").split(' ')))  # <class 'tuple'>
min_max(num_tuple)

3개의 숫자를 입력하세요: 1 2 3
(1, 2, 3)
최소값: 1 최댓값: 3

In [30]:
# 참고: 가변매개변수 이용
def min_max(*numbers):
    # numbers_tuple = tuple(numbers)  # unnecessary. parameter is already tuple
    print("최소값:", min(numbers), "최대값:", max(numbers))

min_max(10, 4, 9)

최소값: 4 최대값: 10

> Ch. 29

주어진 숫자가 짝수인지 확인하는 함수 is_even을 작성하세요. 짝수라면 True를, 아니라면 False를 반환하세요. 함수 내에서 조기 리턴을 활용하세요.

In [24]:
def is_even(number):
    if number % 2 != 0:
        return False
    return True

print(is_even(1))
print(is_even(2))

False
True

> Ch. 30

팩토리얼을 계산하는 재귀 함수 factorial을 작성하세요.

In [26]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n-1)

print(factorial(5))

120

>Ch. 31

문자열 리스트를 받아, 각 문자열의 길이를 출력하는 함수 print_lengths를 작성하세요.

In [27]:
def print_lengths(str_list):
    for str in str_list:
        print(len(str))

print_lengths(['qwer', 'asdfgh', '12345qwert'])

4
6
10

> Ch. 32

두 문자열을 받아서 긴 문자열을 반환하는 함수 longer_string을 작성하세요. 만약 두 문자열의 길이가 같다면, 첫 번째 문자열을 반환하세요.

In [28]:
def longer_string(str1, str2):
    return str1 if len(str1) >= len(str2) else str2

print(longer_string("apple", "banana"))

banana