안녕하세요. 수강생 여러분~! Chapter14 ~ 16 수업은 잘 들으셨나요?

Chapter14 ~ 16의 수업 내용을 바탕으로 아래 문제를 풀어주시면 됩니다.

<br>


[**답변 입력 방법**]

문제 아래에 있는 코드 입력창에 정답코드를 작성하신 후  __▷ 버튼을 클릭해 코드를 실행__ 해보세요<br>

---

__[문제1]__

주어진 정수 x와 자연수 n을 이용해, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 출력해주세요   
<br>

x = 2, n =5

In [102]:
x, n = 2, 5
print(list(range(x, x*(n+1), 2)))


# print([i * x for i in range(1, n + 1)])

# for i in range(1, n + 1):
#     list_arr.append(i * x)

[2, 4, 6, 8, 10]

---

__[문제2]__

전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 *으로 가린 문자열이 출력되도록 코드를 작성해주세요

phone_number = "01012347890"  
<br>

출력 예) "0101234****"

In [104]:
phone_number = "01012347890"

print(phone_number.replace(phone_number[-4:], "*" * len(phone_number[-4:])))


# print(phone_number[:-4], end="")
# for i in range(4):
#     print("*", end="")
# print()

# new_number = phone_number[:-4] + "****"

# new_number = phone_number[:-4].ljust(len(phone_number), '*')

0101234****

---

__[문제3]__

숫자를 건넬 때 일부 자릿수를 영단어로 바꾼 카드를 건네주면 프로도는 원래 숫자를 찾는 게임입니다.

다음은 숫자의 일부 자릿수를 영단어로 바꾸는 예시입니다.

1478 → "one4seveneight"  
234567 → "23four5six7"  
10203 → "1zerotwozero3"    

이렇게 숫자의 일부 자릿수가 영단어로 바뀌어졌거나,   
혹은 바뀌지 않고 그대로인 문자열 s가 주어졌을때
s가 의미하는 원래 숫자를 출력하도록 코드를 작성해주세요

s = "77three4one

---
참고로 각 숫자에 대응되는 영단어는 다음 표와 같습니다.

숫자	영단어  
0	zero  
1	one  
2	two  
3	three  
4	four  
5	five  
6	six  
7	seven  
8	eight  
9	nine

In [105]:
codes = {
    0:'zero',
    1:'one',
    2:'two',
    3:'three',
    4:'four',
    5:'five',
    6:'six',
    7:'seven',
    8:'eight',
    9:'nine'
}
# print(codes.keys())  # dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# print(codes.values())  # dict_values(['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'])
# new_s.replace(tmp, str(list(codes.keys())[list(codes.values()).index(tmp)]))

s = "77three4one"
# s = "one4seveneight"
# s = "23four5six7"
# s = "1zerotwozero3"

## s position
## implement replace()
tmp = ""
new_s = ""  # to prevent @IndexError: string index out of range
for i in range(len(s)):
    if s[i].isdigit():  # 774
        new_s += s[i]
        continue

    tmp += s[i]
    # print(tmp)
    if tmp in codes.values():  # threeone
        new_s += str(list(codes.keys())[list(codes.values()).index(tmp)])  # @TypeError: 'str' object does not support item assignment
        tmp = ""

print(new_s)



## codes position
# for key, value in codes.items():
#     s = s.replace(value, str(key))

# print(int(s))

77341

---

__[문제4]__

행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다.

 행렬 arr1과 arr2가 주어졌을 때, 행렬 덧셈의 결과를 출력하는 코드를 작성해주세요(result와 같은 결과가 출력되도록 작성)

arr1 = [[1,2],[2,3]]

arr2 = [[3,4],[5,6]]

result = [[4,6],[7,9]]

In [106]:
arr1 = [[1,2],[2,3]]
arr2 = [[3,4],[5,6]]

result = []
for i in range(len(arr1)):
    tmp = []
    for j in range(len(arr1[i])):
        tmp.append(arr1[i][j] + arr2[i][j])
    result.append(tmp)


""" result = [[c1 + c2 for c1, c2 in zip(r1, r2)] for r1, r2 in zip(arr1, arr2)] """

print(result)

[[4, 6], [7, 9]]

---

__[문제5]__

양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다.   
예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다.   
주어진 x를 이용해 x가 하샤드 수인지 아닌지 검사하는 코드를 작성해주세요

x = 17

----

입출력 예시
x	결과값  
10	true  
12	true  
11	false  
13	false

In [108]:
x = 17
xsum = 0
for i in range(len(str(x))):
    xsum += int(str(x)[i])
if x % xsum == 0:
    print("true")
else:
    print("false")


# num_list = list(map(int, str(x)))
# result = x % sum(num_list) == 0
# print(result)

false

---

__[문제6]__

String형 배열 seoul의 element중 "Kim"의 인덱스 x를 찾아, "김서방은 x에 있다"는 String을 출력하는 코드를 작성해주세요.   

seoul에 "Kim"은 오직 한 번만 나타나며 잘못된 값이 입력되는 경우는 없습니다.

seoul = ["Jane", "Kim"]

<br>
출력 예) "김서방은 1에 있다"

In [109]:
seoul = ["Jane", "Kim"]

print(f"김서방은 {seoul.index('Kim')}에 있다")


# for i in range(len(seoul)):
#     if seoul[i] == "Kim":
#         print(f"김서방은 {i}에 있다")

김서방은 1에 있다

---

__[문제7]__

0부터 9까지의 숫자 중 일부가 들어있는 정수 배열 numbers가 주어집니다.   
numbers에서 찾을 수 없는 0부터 9까지의 숫자를 모두 찾아 더한 수를 출력해주세요

numbers = [5,8,1,0,6,9]

In [110]:
# del sum

numbers = [5,8,1,0,6,9]

zerotonine = "0123456789"
for i in range(len(numbers)):
    zerotonine = zerotonine.replace(str(numbers[i]), "")

print(sum(list(map(int, list(zerotonine)))))


# full_set = set(range(10))
# numbers_set = set(numbers)
# missing_numbers = full_set - numbers_set
# result = sum(missing_numbers)
# print(result)

16